// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJrwuI6rMfAxLBmj7sDcB2QzId5Sg52cg',
    appId: '1:391020026085:web:953f4d230ec8d47d235c0c',
    messagingSenderId: '391020026085',
    projectId: 'fair-n-square-app',
    authDomain: 'fair-n-square-app.firebaseapp.com',
    storageBucket: 'fair-n-square-app.appspot.com',
    measurementId: 'G-JHSSDEXQTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCikVqO4E7MQ_eAtgUiObxhF6lx_CfJCjg',
    appId: '1:391020026085:android:b0cbbdb3a06c4fc8235c0c',
    messagingSenderId: '391020026085',
    projectId: 'fair-n-square-app',
    storageBucket: 'fair-n-square-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEu3p2vnohjtUImuDvTd_BRHcZS88Df6g',
    appId: '1:391020026085:ios:748c8220adf9c3a7235c0c',
    messagingSenderId: '391020026085',
    projectId: 'fair-n-square-app',
    storageBucket: 'fair-n-square-app.appspot.com',
    iosClientId: '391020026085-d35s167jqn9fstrv79ju8drg1ebkn9ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.fairAndSquare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEu3p2vnohjtUImuDvTd_BRHcZS88Df6g',
    appId: '1:391020026085:ios:748c8220adf9c3a7235c0c',
    messagingSenderId: '391020026085',
    projectId: 'fair-n-square-app',
    storageBucket: 'fair-n-square-app.appspot.com',
    iosClientId: '391020026085-d35s167jqn9fstrv79ju8drg1ebkn9ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.fairAndSquare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJrwuI6rMfAxLBmj7sDcB2QzId5Sg52cg',
    appId: '1:391020026085:web:4af39931903ce274235c0c',
    messagingSenderId: '391020026085',
    projectId: 'fair-n-square-app',
    authDomain: 'fair-n-square-app.firebaseapp.com',
    storageBucket: 'fair-n-square-app.appspot.com',
    measurementId: 'G-8PMSZ3RNMM',
  );
}
